### ISSUE TITLE
How to get the Treebank data

### ISSUE THREAD

**Issue by cwarny** [acrola/RnnInduceRegularGrammar#1]
Hi! Thanks for the work and the interesting paper! Can you clarify how to download the Treebank data? I followed the link mentioned in the README but can't find anything in that web archive page. Thanks for the help!

**Comment by aviclu** [comment]
Hi, 
Thanks for your interest in out work.
The Penn Treebank dataset is not for free, you should purchase it online and then you can download and use it.
Avi
